# Site settings
title: MuVI - Museus Virtuais Interativos
email: guijocargo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este blog tem por objetivo fornecer informações a cerca de um projeto para 
  as disciplinas de Interface Humano-Computador (IHC) e Projeto e 
  Desenvolvimento de Sistemas (PDS) do curso de Bacharel em Ciência da 
  Computação do campus de Sorocaba da Unviersidade Federal de São Carlos.
baseurl: "/MUVI/" # the subpath of your site, e.g. /blog/
url: "http://guilhermejcgois.github.io/MUVI/" # the base hostname & protocol for your site
twitter_username: guilhermejcgois
github_username:  guilhermejcgois

# Build settings
markdown: kramdown
